apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ include "hello-world-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  envName: {{ .Values.config.envName | quote }}
